apiVersion: v1
kind: Pod
metadata:
  name: kind-pod
  labels:
    target: "true"
spec:
  containers:
  - name: ubuntu
    image: lawrencegripper/kink:latest
    volumeMounts:
    - mountPath: /lib/modules
      name: modules
      readOnly: true
    - mountPath: /sys/fs/cgroup
      name: cgroup
    - name: dind-storage
      mountPath: /var/lib/docker
    resources:
      requests:
        cpu: 1
        memory: 4000Mi
    securityContext:
      privileged: true
    imagePullPolicy: Always
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    - name: dind-storage
      emptyDir: {}

